#[target.x86_64-unknown-linux-gnu]
#linker = "x86_64-unknown-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

#CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc
#export CC_x86_64_unknown_linux_gnu=x86_64-unknown-linux-gnu-gcc
#export CXX_x86_64_unknown_linux_gnu=x86_64-unknown-linux-gnu-g++
#export AR_x86_64_unknown_linux_gnu=x86_64-unknown-linux-gnu-ar